CREATE-SCRIPT-CREATE-TABLE:
	go run main.go next-script create --version-type TIME --description create_table

CREATE-SCRIPT-ALTER-TABLE:
	go run main.go next-script create --version-type TIME --description alter_table

UPDATE-SCRIPT:
	go run main.go next-script update

MIGRATE-ALL:
	go run main.go migrate all

MIGRATE-INC:
	go run main.go migrate inc

MIGRATE-DEC:
	go run main.go migrate dec
